import {
  useCallback,
  useEffect,
  useRef,
  useState
} from "react";
import {
  CheckCircle2,
  ClipboardList,
  Loader2,
  RefreshCw,
  XCircle
} from "lucide-react";
import {
  createMaterialQuizAttempt,
  createQuizAttempt,
  submitQuizAttempt
} from "../quizzes/quizzesAPI";

//A multiple-choice quiz built from a note.
//
//The generated questions arrive without their answers, and the server
//grades the submission, so neither the score nor the XP it earns can be
//invented in the browser.
//
//A quiz can also be built from a lesson PDF: pass materialId instead of
//noteId and the same component works, because the server grades both the
//same way.
//
//autoGenerate builds the first quiz as soon as a source is chosen; the
//Study Notes tab asks for a click instead.
function Quiz({
  noteId,
  materialId,
  autoGenerate = false
}) {
  const label = materialId ? "lesson" : "note";

  const [quiz, setQuiz] = useState(null);
  const [answers, setAnswers] = useState({});
  const [result, setResult] = useState(null);
  const [loading, setLoading] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState("");

  const handleGenerate = useCallback(async () => {
    setLoading(true);
    setError("");

    try {
      const attempt = materialId
        ? await createMaterialQuizAttempt(materialId)
        : await createQuizAttempt(noteId);

      setQuiz(attempt);
      setAnswers({});
      setResult(null);

    } catch (err) {
      setError(
        err.message || "Unable to generate a quiz"
      );
    } finally {
      setLoading(false);
    }
  }, [noteId, materialId]);

  //StrictMode runs effects twice in development, and each run would cost
  //an AI call and a stored attempt, so the first build happens once.
  const autoGenerated = useRef(false);

  useEffect(() => {
    if (!autoGenerate || autoGenerated.current) {
      return;
    }

    autoGenerated.current = true;

    handleGenerate();
  }, [autoGenerate, handleGenerate]);

  const questions = quiz?.questions || [];

  const handleSelect = (questionIndex, option) => {
    //the answers are locked once the server has marked them
    if (result) {
      return;
    }

    setAnswers((current) => ({
      ...current,
      [questionIndex]: option
    }));
  };

  const allAnswered =
    questions.length > 0 &&
    questions.every(
      (_, index) => answers[index] !== undefined
    );

  const handleSubmit = async () => {
    setSubmitting(true);
    setError("");

    try {
      const graded = await submitQuizAttempt(
        quiz._id,
        questions.map(
          (_, index) => answers[index] ?? null
        )
      );

      setResult(graded);

    } catch (err) {
      setError(
        err.message || "Unable to submit your answers"
      );
    } finally {
      setSubmitting(false);
    }
  };

  if (!quiz) {
    return (
      <div className="text-center py-14">
        <ClipboardList
          size={42}
          className="mx-auto text-gray-400 mb-4"
        />

        <p className="text-gray-600">
          Test yourself with a multiple-choice quiz
          from this {label}.
        </p>

        {error && (
          <p className="text-sm text-red-600 mt-3">
            {error}
          </p>
        )}

        <button
          type="button"
          onClick={handleGenerate}
          disabled={loading}
          className="mt-5 inline-flex items-center gap-2 px-5 py-2.5 rounded-xl bg-blue-500 hover:bg-blue-600 disabled:opacity-50 disabled:cursor-not-allowed text-white text-sm font-semibold cursor-pointer transition-colors"
        >
          {loading ? (
            <>
              <Loader2
                size={16}
                className="animate-spin"
              />
              Building quiz...
            </>
          ) : (
            "Generate Quiz"
          )}
        </button>
      </div>
    );
  }

  return (
    <div className="space-y-5">

      <div className="flex items-center justify-between">
        <p className="text-sm text-gray-500">
          {questions.length} questions
        </p>

        <button
          type="button"
          onClick={handleGenerate}
          disabled={loading}
          className="inline-flex items-center gap-2 text-sm text-gray-500 hover:text-gray-800 disabled:opacity-50 cursor-pointer"
        >
          <RefreshCw size={14} />
          New quiz
        </button>
      </div>

      {result && (
        <div className="bg-blue-50 border border-blue-200 rounded-2xl p-5">
          <p className="text-sm text-blue-700 font-medium">
            Your score
          </p>

          <p className="text-3xl font-bold text-blue-700 mt-1">
            {result.correct} / {result.total}
          </p>

          <p className="text-sm text-blue-700 mt-2">
            {result.xpAwarded > 0
              ? `+${result.xpAwarded} XP earned`
              : `No new XP — you had already earned the most this ${label}'s quiz is worth.`}
          </p>
        </div>
      )}

      <ol className="space-y-5">
        {questions.map((question, questionIndex) => {
          const chosen = answers[questionIndex];

          //only present once the server has marked the quiz
          const review =
            result?.results?.[questionIndex];

          return (
            <li
              key={questionIndex}
              className="bg-white border border-gray-200 rounded-2xl p-5 shadow-sm"
            >
              <p className="font-medium text-gray-800">
                {questionIndex + 1}. {question.question}
              </p>

              <div className="mt-4 space-y-2">
                {question.options.map((option) => {
                  const isChosen = chosen === option;

                  const isCorrect =
                    review?.correctAnswer === option;

                  let optionClass =
                    "border-gray-200 hover:border-blue-300";

                  if (result && isCorrect) {
                    optionClass =
                      "border-green-400 bg-green-50";
                  } else if (
                    result &&
                    isChosen &&
                    !isCorrect
                  ) {
                    optionClass =
                      "border-red-400 bg-red-50";
                  } else if (isChosen) {
                    optionClass =
                      "border-blue-400 bg-blue-50";
                  }

                  return (
                    <button
                      key={option}
                      type="button"
                      onClick={() =>
                        handleSelect(
                          questionIndex,
                          option
                        )
                      }
                      className={`w-full flex items-center justify-between gap-3 text-left px-4 py-3 rounded-xl border text-sm text-gray-700 transition-colors cursor-pointer ${optionClass}`}
                    >
                      <span>{option}</span>

                      {result && isCorrect && (
                        <CheckCircle2
                          size={16}
                          className="text-green-600 shrink-0"
                        />
                      )}

                      {result &&
                        isChosen &&
                        !isCorrect && (
                          <XCircle
                            size={16}
                            className="text-red-600 shrink-0"
                          />
                        )}
                    </button>
                  );
                })}
              </div>

              {result && !chosen && (
                <p className="text-xs text-gray-500 mt-3">
                  Not answered — correct answer:{" "}
                  {review?.correctAnswer}
                </p>
              )}
            </li>
          );
        })}
      </ol>

      {!result && (
        <button
          type="button"
          onClick={handleSubmit}
          disabled={!allAnswered || submitting}
          className="w-full inline-flex items-center justify-center gap-2 py-3 rounded-xl bg-blue-500 hover:bg-blue-600 disabled:opacity-50 disabled:cursor-not-allowed text-white text-sm font-semibold cursor-pointer transition-colors"
        >
          {submitting ? (
            <>
              <Loader2
                size={16}
                className="animate-spin"
              />
              Marking...
            </>
          ) : allAnswered ? (
            "Submit Answers"
          ) : (
            "Answer every question to submit"
          )}
        </button>
      )}

      {error && (
        <p className="text-sm text-red-600">
          {error}
        </p>
      )}

    </div>
  );
}

export default Quiz;
